#include<bits/stdc++.h>
using namespace std;

int main(){
	ios::sync_with_studio(0);
	freopen("output.txt", "w", stdout);

	string a, b;
	//cin >> a >> b;
	//cout << "hello world" << " " << a << " " << b;
	//scanf("%s %s",&a,&b);
	//printf("%s %s",a,b);

	//getline(cin, a);
	//cout << a;
	/*
	while( cin > a){
		cout << a;
	}
	*/
	int a = 2;
	long long b = 5LL;
	b = b * (long long)a;
	cout << b;
	return 0;
}